apiVersion: v2
name: huna
description: A Helm chart for Kubernetes
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: ""
dependencies:
  - name: regcred
    version: "0.1.0"
    repository: "https://colearendt.github.io/helm"
  - name: mongodb
    version: "0.6.3"
    repository: "https://groundhog2k.github.io/helm-charts/"
  - name: redis
    version: "0.7.10"
    repository: "https://groundhog2k.github.io/helm-charts/"
  - name: redis-commander
    version: "0.1.15"
    repository: "https://kfirfer.github.io/charts/"
  - name: dex
    version: "0.16.0"
    repository: "https://charts.dexidp.io"
  - name: emqx
    version: "5.5.0"
    repository: "https://repos.emqx.io/charts"
  - name: huna-ui
    version: "0.0.213"
    repository: "oci://ghcr.io/mars-office"
  - name: huna-parkinglots
    version: "0.0.110"
    repository: "oci://ghcr.io/mars-office"
  - name: huna-users
    version: "0.0.32"
    repository: "oci://ghcr.io/mars-office"
  - name: huna-iot
    version: "0.3.6"
    repository: "oci://ghcr.io/mars-office"
  - name: huna-detection
    version: "0.0.32"
    repository: "oci://ghcr.io/mars-office"
  - name: huna-ota
    version: "0.0.37"
    repository: "oci://ghcr.io/mars-office"
  - name: huna-signalr
    version: "0.0.21"
    repository: "oci://ghcr.io/mars-office"
