regcred:
  registryCredentials:
    - url: ghcr.io
      username: 'mars-office'
      password: '${GH_TOKEN}'

mongodb:
  storage:
    requestedSize: 10Gi
  settings:
    rootPassword: '${MONGODB_PASSWORD}'