environment: uat

regcred:
  registryCredentials:
    - url: ghcr.io
      username: 'mars-office'
      password: '${GH_TOKEN}'

mongodb:
  settings:
    rootPassword: '${MONGODB_PASSWORD}'
  storage:
    requestedSize: 10Gi

redis:
  password: '${REDIS_PASSWORD}'

rabbitmq:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: rabbitmq.uat.huna2.com
        paths:
          - '/'
    tls:
      - secretName: rabbitmq-ingress-tls
        hosts:
          - rabbitmq.uat.huna2.com
  authentication:
    password: '${RABBITMQ_PASSWORD}'
    erlangCookie: '${RABBITMQ_ERLANG_COOKIE}'

mongo-express:
  mongodbAdminPassword: '${MONGODB_PASSWORD}'
  basicAuthPassword: '${MONGO_EXPRESS_PASSWORD}'
  siteCookieSecret: '${MONGO_EXPRESS_SECRET}'
  siteSessionSecret: '${MONGO_EXPRESS_SECRET}'
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: mongodb.uat.huna2.com
        paths:
          - '/'
    tls:
      - secretName: mongodb-ingress-tls
        hosts:
          - mongodb.uat.huna2.com

redis-commander:
  redis:
    password: '${REDIS_PASSWORD}'
  httpAuth:
    password: '${REDIS_COMMANDER_PASSWORD}'
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: redis.uat.huna2.com
        paths:
          - '/'
    tls:
      - secretName: redis-ingress-tls
        hosts:
          - redis.uat.huna2.com

dex:
  config:
    issuer: "https://dex.uat.huna2.com"
    staticClients:
      - id: ui
        redirectURIs:
          - 'https://uat.huna2.com/'
        name: 'UI'
        public: true
    connectors:
      - type: google
        id: google
        name: Google
        config:
          clientID: '${GOOGLE_CLIENT_ID}'
          clientSecret: '${GOOGLE_CLIENT_SECRET}'
          redirectURI: https://dex.uat.huna2.com/callback
      - type: microsoft
        id: microsoft
        name: Microsoft
        config:
          clientID: '${MICROSOFT_CLIENT_ID}'
          clientSecret: '${MICROSOFT_CLIENT_SECRET}'
          redirectURI: https://dex.uat.huna2.com/callback
      - type: oauth
        id: facebook 
        name: Facebook
        config:
          clientID: '${FACEBOOK_CLIENT_ID}'
          clientSecret: '${FACEBOOK_CLIENT_SECRET}'
          redirectURI: https://dex.uat.huna2.com/callback
          tokenURL: https://graph.facebook.com/v16.0/oauth/access_token
          authorizationURL: https://facebook.com/dialog/oauth
          userInfoURL: https://graph.facebook.com/v16.0/me?fields=id,name,email
          scopes:
            - public_profile
            - email
          claimMapping:
            userNameKey: 'name'
            # preferredUsernameKey: ''
            # groupsKey: ''
            emailKey: 'email'
            # emailVerifiedKey: ''

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts: 
      - host: dex.uat.huna2.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: dex-ingress-tls
        hosts:
          - dex.uat.huna2.com


huna-ui:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: uat.huna2.com
        paths:
          - path: '/'
            pathType: ImplementationSpecific
    tls:
      - secretName: huna-ingress-tls
        hosts:
          - uat.huna2.com

opa:
  styraDasToken: '${STYRA_DAS_TOKEN}'
