regcred:
  registryCredentials:
    - url: ghcr.io
      username: 'mars-office'
      password: '${GH_TOKEN}'

mongodb:
  settings:
    rootPassword: '${MONGODB_PASSWORD}'
  storage:
    requestedSize: 10Gi

redis:
  password: '${REDIS_PASSWORD}'

rabbitmq:
  ingress:
    hosts:
      - host: rabbitmq.dev.huna2.com
        paths:
          - '/'
    tls:
      - secretName: rabbitmq-ingress-tls
        hosts:
          - rabbitmq.dev.huna2.com
  authentication:
    password: '${RABBITMQ_PASSWORD}'
    erlangCookie: '${RABBITMQ_ERLANG_COOKIE}'

mongo-express:
  mongodbAdminPassword: '${MONGODB_PASSWORD}'
  basicAuthPassword: '${MONGO_EXPRESS_PASSWORD}'
  siteCookieSecret: '${MONGO_EXPRESS_SECRET}'
  siteSessionSecret: '${MONGO_EXPRESS_SECRET}'
  ingress:
    hosts:
      - host: mongodb.dev.huna2.com
        paths:
          - '/'
    tls:
      - secretName: mongodb-ingress-tls
        hosts:
          - mongodb.dev.huna2.com

redis-commander:
  redis:
    password: '${REDIS_PASSWORD}'
  httpAuth:
    password: '${REDIS_COMMANDER_PASSWORD}'
  ingress:
    hosts:
      - host: redis.dev.huna2.com
        paths:
          - '/'
    tls:
      - secretName: redis-ingress-tls
        hosts:
          - redis.dev.huna2.com

dex:
  config:
    issuer: "https://dex.dev.huna2.com"
    connectors:
      - type: google
        id: google
        name: Google
        config:
          # Connector config values starting with a "$" will read from the environment.
          clientID: $GOOGLE_CLIENT_ID
          clientSecret: $GOOGLE_CLIENT_SECRET
          # Dex's issuer URL + "/callback"
          redirectURI: http://dex.dev.huna2.com/callback/google
          
      - type: microsoft
        # Required field for connector id.
        id: microsoft
        # Required field for connector name.
        name: Microsoft
        config:
          # Credentials can be string literals or pulled from the environment.
          clientID: $MICROSOFT_APPLICATION_ID
          clientSecret: $MICROSOFT_CLIENT_SECRET
          redirectURI: http://dex.dev.huna2.com/callback/microsoft
      
      - type: facebook
        # Required field for connector id.
        id: facebook
        # Required field for connector name.
        name: Facebook
        config:
          # Credentials can be string literals or pulled from the environment.
          clientID: $FACEBOOK_CLIENT_ID
          clientSecret: $FACEBOOK_CLIENT_SECRET
          redirectURI: http://dex.dev.huna2.com/callback/facebook
          
  ingress:
    hosts: 
      - host: dex.dev.huna2.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: dex-ingress-tls
        hosts:
          - dex.dev.huna2.com