environment: local

regcred:
  nameOverride: 'regcred'
  fullnameOverride: 'regcred'
  registryCredentials:
    - url: ghcr.io
      username: ''
      password: ''

mongodb:
  podAnnotations:
    linkerd.io/inject: enabled
  storage:
    requestedSize: 10Gi
  settings:
    rootUsername: 'admin'
    rootPassword: ''
  
dex:
  rbac:
    create: false
    createClusterScoped: false
  persistence:
    size: 1Gi
  volumes:
    - name: dex-data
      persistentVolumeClaim:
        claimName: huna-dex-data
  volumeMounts:
    - mountPath: "/data"
      name: dex-data
  config:
    staticClients:
      - id: ui
        redirectURIs:
          - 'https://local.huna2.com/'
        name: 'UI'
        public: true
    expiry:
      idTokens: "15m"
      refreshTokens:
        disableRotation: true
        validIfNotUsedFor: "2160h" # 90 days
        reuseInterval: "2160h"
    issuer: "https://dex.local.huna2.com"
    web:
      allowedOrigins: ['*']
    storage:
      type: sqlite3
      config:
        file: /data/dex.db
    enablePasswordDB: false
    oauth2:
      skipApprovalScreen: true
    frontend:
      issuer: huna2
      theme: dark
      alwaysShowLoginScreen: false
  podAnnotations:
    linkerd.io/inject: enabled

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: root-ca
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts: 
      - host: dex.local.huna2.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: dex-ingress-tls
        hosts:
          - dex.local.huna2.com

emqx:
  hostname: emqx.local.huna2.com
  replicaCount: 1
  emqxConfig:
    EMQX_DASHBOARD__DEFAULT_USERNAME: "admin"
    EMQX_DASHBOARD__DEFAULT_PASSWORD: ""
    EMQX_LISTENERS__WSS__DEFAULT__ENABLE: "false"
    EMQX_OPENTELEMETRY__TRACES__ENABLE: "true"
    EMQX_OPENTELEMETRY__EXPORTER__ENDPOINT: "http://collector.linkerd-jaeger:4317"
    EMQX_LISTENERS__WS__DEFAULT__ENABLE: "false"
    EMQX_AUTHORIZATION__SOURCES: "[ { enable = true url = \\\"http://localhost:8181/v1/data/com/huna/authz/allow?input=%7B%22type%22%3A%22mqtt%22%2C%22username%22%3A%22${username}%22%2C%22action%22%3A%22${action}%22%2C%22topic%22%3A%22${topic}%22%2C%22peerhost%22%3A%22${peerhost}%22%7D\\\" type = http method = \\\"get\\\" } ]"

  podAnnotations:
    linkerd.io/inject: enabled
  persistence:
    enabled: true
    size: 5Gi
  ingress:
    dashboard:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: root-ca
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/service-upstream: "true"
      hosts:
        - emqx-admin.local.huna2.com
      tls:
        - secretName: emqx-dashboard-ingress-tls
          hosts:
            - emqx-admin.local.huna2.com


redis:
  password: ''
  redisConfig: |
    requirepass
  useDeploymentWhenNonHA: false
  podAnnotations:
    linkerd.io/inject: enabled
  storage:
    requestedSize: 1Gi

huna-ui:
  imagePullSecrets:
    - name: regcred
  podAnnotations:
    linkerd.io/inject: enabled
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: root-ca
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: local.huna2.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: huna-ingress-tls
        hosts:
          - local.huna2.com

huna-users:
  env:
    - name: NODE_ENV
      value: local
    - name: OTEL_TRACES_EXPORTER
      value: 'none'
    - name: OTEL_METRICS_EXPORTER
      value: 'none'
    - name: OTEL_LOGS_EXPORTER
      value: 'none'
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: ''
    - name: OTEL_SERVICE_NAME
      value: 'huna-users'
    - name: OTEL_PROPAGATORS
      value: 'b3,b3multi'
    - name: OTEL_SDK_DISABLED
      value: 'true'
    - name: OTEL_NODE_RESOURCE_DETECTORS
      value: 'env,host,os'
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: huna
          key: mongodbPassword
  imagePullSecrets:
    - name: regcred
  podAnnotations:
    linkerd.io/inject: enabled
  podLabels:
    opa: "true"
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: local.huna2.com
        paths:
          - path: /api/users
            pathType: ImplementationSpecific

huna-signalr:
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OTEL_TRACES_EXPORTER
      value: 'none'
    - name: OTEL_METRICS_EXPORTER
      value: 'none'
    - name: OTEL_LOGS_EXPORTER
      value: 'none'
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: ''
    - name: OTEL_SERVICE_NAME
      value: 'huna-signalr'
    - name: OTEL_PROPAGATORS
      value: 'b3,b3multi'
    - name: OTEL_SDK_DISABLED
      value: 'true'
    - name: OTEL_NODE_RESOURCE_DETECTORS
      value: 'env,host,os'
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: huna
          key: redisPassword
  imagePullSecrets:
    - name: regcred
  podAnnotations:
    linkerd.io/inject: enabled
  podLabels:
    opa: "true"
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
      nginx.ingress.kubernetes.io/affinity-mode: balanced
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    hosts:
      - host: local.huna2.com
        paths:
          - path: /api/signalr
            pathType: ImplementationSpecific


opa:
  styraDasToken: ''
