regcred:
  registryCredentials:
    - url: ghcr.io
      username: 'mars-office'
      password: '${GH_TOKEN}'

mongodb:
  settings:
    rootPassword: '${MONGODB_PASSWORD}'
  storage:
    requestedSize: 10Gi

redis:
  password: '${REDIS_PASSWORD}'

rabbitmq:
  ingress:
    hosts:
      - host: rabbitmq.dev.huna2.com
        paths:
          - '/'
    tls:
      - secretName: rabbitmq-ingress-tls
        hosts:
          - rabbitmq.dev.huna2.com
  authentication:
    password: '${RABBITMQ_PASSWORD}'
    erlangCookie: '${RABBITMQ_ERLANG_COOKIE}'