environment: dev

regcred:
  registryCredentials:
    - url: ghcr.io
      username: 'mars-office'
      password: '${GH_TOKEN}'

mongodb:
  settings:
    rootPassword: '${MONGODB_PASSWORD}'
  storage:
    requestedSize: 10Gi

dex:
  config:
    issuer: "https://dex.dev.huna2.com"
    staticClients:
      - id: ui
        redirectURIs:
          - 'https://dev.huna2.com/'
        name: 'UI'
        public: true
    connectors:
      - type: google
        id: google
        name: Google
        config:
          clientID: '${GOOGLE_CLIENT_ID}'
          clientSecret: '${GOOGLE_CLIENT_SECRET}'
          redirectURI: https://dex.dev.huna2.com/callback
      - type: microsoft
        id: microsoft
        name: Microsoft
        config:
          clientID: '${MICROSOFT_CLIENT_ID}'
          clientSecret: '${MICROSOFT_CLIENT_SECRET}'
          redirectURI: https://dex.dev.huna2.com/callback
      - type: oauth
        id: facebook 
        name: Facebook
        config:
          clientID: '${FACEBOOK_CLIENT_ID}'
          clientSecret: '${FACEBOOK_CLIENT_SECRET}'
          redirectURI: https://dex.dev.huna2.com/callback
          tokenURL: https://graph.facebook.com/v16.0/oauth/access_token
          authorizationURL: https://facebook.com/dialog/oauth
          userInfoURL: https://graph.facebook.com/v16.0/me?fields=id,name,email
          scopes:
            - public_profile
            - email
          claimMapping:
            userNameKey: 'name'
            # preferredUsernameKey: ''
            # groupsKey: ''
            emailKey: 'email'
            # emailVerifiedKey: ''

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/issuer: null
    hosts:
      - host: dex.dev.huna2.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: dex-ingress-tls
        hosts:
          - dex.dev.huna2.com

emqx:
  hostname: emqx.dev.huna2.com
  emqxConfig:
    EMQX_DASHBOARD__DEFAULT_PASSWORD: '${EMQX_DASHBOARD_PASSWORD}'
  ingress:
    dashboard:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        cert-manager.io/issuer: null
      hosts:
        - emqx-admin.dev.huna2.com
      tls:
        - secretName: emqx-dashboard-ingress-tls
          hosts:
            - emqx-admin.dev.huna2.com

redis:
  password: '${REDIS_PASSWORD}'
  redisConfig: |
    requirepass ${REDIS_PASSWORD}

redis-commander:
  redis:
    password: '${REDIS_PASSWORD}'
  httpAuth:
    password: '${REDIS_ADMIN_PASSWORD}'
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/issuer: null
    hosts: 
      - host: redis-commander.dev.huna2.com
        paths:
          - '/'
    tls:
      - secretName: redis-commander-ingress-tls
        hosts:
          - redis-commander.dev.huna2.com

huna-ui:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/issuer: null
    hosts:
      - host: dev.huna2.com
        paths:
          - path: '/'
            pathType: ImplementationSpecific
    tls:
      - secretName: huna-ingress-tls
        hosts:
          - dev.huna2.com

huna-parkinglots:
  env:
    - name: IOT_CA_CRT
      valueFrom:
        secretKeyRef:
          name: huna-intermediate-ca-secret
          key: 'tls.crt'
    - name: ROOT_CA_CRT
      valueFrom:
        secretKeyRef:
          name: huna-intermediate-ca-secret
          key: 'ca.crt'
    - name: IOT_CA_KEY
      valueFrom:
        secretKeyRef:
          name: huna-intermediate-ca-secret
          key: 'tls.key'
    - name: EMQX_CLIENT_CRT
      valueFrom:
        secretKeyRef:
          name: huna-mqtt-client-cert-secret
          key: 'tls.crt'
    - name: EMQX_CLIENT_KEY
      valueFrom:
        secretKeyRef:
          name: huna-mqtt-client-cert-secret
          key: 'tls.key'
    - name: EMQX_CA_CRT
      valueFrom:
        secretKeyRef:
          name: huna-mqtt-client-cert-secret
          key: 'ca.crt'
    - name: NODE_ENV
      value: dev
    - name: OTEL_TRACES_EXPORTER
      value: 'otlp'
    - name: OTEL_METRICS_EXPORTER
      value: 'otlp'
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: 'http://collector.linkerd-jaeger:4318'
    - name: OTEL_SERVICE_NAME
      value: 'huna-parkinglots'
    - name: OTEL_PROPAGATORS
      value: 'b3,b3multi'
    - name: OTEL_SDK_DISABLED
      value: 'false'
    - name: OTEL_NODE_RESOURCE_DETECTORS
      value: 'env,host,os'
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: huna
          key: mongodbPassword
  ingress:
    hosts:
      - host: dev.huna2.com
        paths:
          - path: /api/parkinglots
            pathType: ImplementationSpecific

huna-users:
  env:
    - name: NODE_ENV
      value: dev
    - name: OTEL_TRACES_EXPORTER
      value: 'otlp'
    - name: OTEL_METRICS_EXPORTER
      value: 'otlp'
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: 'http://collector.linkerd-jaeger:4318'
    - name: OTEL_SERVICE_NAME
      value: 'huna-users'
    - name: OTEL_PROPAGATORS
      value: 'b3,b3multi'
    - name: OTEL_SDK_DISABLED
      value: 'false'
    - name: OTEL_NODE_RESOURCE_DETECTORS
      value: 'env,host,os'
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: huna
          key: mongodbPassword
  ingress:
    hosts:
      - host: dev.huna2.com
        paths:
          - path: /api/users
            pathType: ImplementationSpecific

huna-signalr:
  env:
    - name: EMQX_CLIENT_CRT
      valueFrom:
        secretKeyRef:
          name: huna-mqtt-client-cert-secret
          key: 'tls.crt'
    - name: EMQX_CLIENT_KEY
      valueFrom:
        secretKeyRef:
          name: huna-mqtt-client-cert-secret
          key: 'tls.key'
    - name: EMQX_CA_CRT
      valueFrom:
        secretKeyRef:
          name: huna-mqtt-client-cert-secret
          key: 'ca.crt'
    - name: ASPNETCORE_ENVIRONMENT
      value: Staging
    - name: OTEL_TRACES_EXPORTER
      value: 'otlp'
    - name: OTEL_METRICS_EXPORTER
      value: 'otlp'
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: 'http://collector.linkerd-jaeger:4318'
    - name: OTEL_SERVICE_NAME
      value: 'huna-signalr'
    - name: OTEL_PROPAGATORS
      value: 'b3,b3multi'
    - name: OTEL_SDK_DISABLED
      value: 'false'
    - name: OTEL_NODE_RESOURCE_DETECTORS
      value: 'env,host,os'
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: huna
          key: redisPassword
  ingress:
    hosts:
      - host: dev.huna2.com
        paths:
          - path: /api/signalr
            pathType: ImplementationSpecific

ota:
  hostname: ota.dev.huna2.com
detection:
  hostname: detection.dev.huna2.com

huna-ota:
  env:
    - name: NODE_ENV
      value: dev
    - name: OTEL_TRACES_EXPORTER
      value: 'otlp'
    - name: OTEL_METRICS_EXPORTER
      value: 'otlp'
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: 'http://collector.linkerd-jaeger:4318'
    - name: OTEL_SERVICE_NAME
      value: 'huna-ota'
    - name: OTEL_PROPAGATORS
      value: 'b3,b3multi'
    - name: OTEL_SDK_DISABLED
      value: 'false'
    - name: OTEL_NODE_RESOURCE_DETECTORS
      value: 'env,host,os'
  ingress:
    hosts:
      - host: ota.dev.huna2.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: huna-ota-server-cert-secret
        hosts:
          - ota.dev.huna2.com

huna-detection:
  roboflowApiToken: '${ROBOFLOW_API_TOKEN}'
  env:
    - name: EMQX_CLIENT_CRT
      valueFrom:
        secretKeyRef:
          name: huna-mqtt-client-cert-secret
          key: 'tls.crt'
    - name: EMQX_CLIENT_KEY
      valueFrom:
        secretKeyRef:
          name: huna-mqtt-client-cert-secret
          key: 'tls.key'
    - name: EMQX_CA_CRT
      valueFrom:
        secretKeyRef:
          name: huna-mqtt-client-cert-secret
          key: 'ca.crt'
    - name: NODE_ENV
      value: dev
    - name: OTEL_TRACES_EXPORTER
      value: 'otlp'
    - name: OTEL_METRICS_EXPORTER
      value: 'otlp'
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: 'http://collector.linkerd-jaeger:4318'
    - name: OTEL_SERVICE_NAME
      value: 'huna-detection'
    - name: OTEL_PROPAGATORS
      value: 'b3,b3multi'
    - name: OTEL_SDK_DISABLED
      value: 'false'
    - name: OTEL_NODE_RESOURCE_DETECTORS
      value: 'env,host,os'
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: huna
          key: mongodbPassword
    - name: ROBOFLOW_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: huna
          key: roboflowApiToken
  ingress:
    hosts:
      - host: detection.dev.huna2.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: huna-detection-server-cert-secret
        hosts:
          - detection.dev.huna2.com

opa:
  styraDasToken: '${STYRA_DAS_TOKEN}'

iotCa:
  ou: dev.huna2.com