regcred:
  nameOverride: 'regcred'
  fullnameOverride: 'regcred'
  registryCredentials:
    - url: ghcr.io
      username: ''
      password: ''

mongodb:
  podAnnotations:
    linkerd.io/inject: enabled
  storage:
    requestedSize: 10Gi
  settings:
    rootUsername: 'root'
    rootPassword: ''

redis:
  password: ''
  haMode:
    enabled: false
  podAnnotations:
    linkerd.io/inject: enabled
  storage:
    requestedSize: 1Gi
  env:
    - name: REDISPASSWORD
      valueFrom:
        secretKeyRef:
          name: huna
          key: redisPassword
  args:
    - '--requirepass $(REDISPASSWORD)'
    - '--protected-mode yes'