regcred:
  registryCredentials:
    - url: ghcr.io
      username: 'mars-office'
      password: '${GH_TOKEN}'

mongodb:
  settings:
    rootPassword: '${MONGODB_PASSWORD}'
  storage:
    requestedSize: 10Gi

redis:
  password: '${REDIS_PASSWORD}'

rabbitmq:
  ingress:
    hosts:
      - host: rabbitmq.huna2.com
        paths:
          - '/'
    tls:
      - secretName: rabbitmq-ingress-tls
        hosts:
          - rabbitmq.huna2.com
  authentication:
    password: '${RABBITMQ_PASSWORD}'
    erlangCookie: '${RABBITMQ_ERLANG_COOKIE}'

mongo-express:
  mongodbAdminPassword: '${MONGODB_PASSWORD}'
  basicAuthPassword: '${MONGO_EXPRESS_PASSWORD}'
  siteCookieSecret: '${MONGO_EXPRESS_SECRET}'
  siteSessionSecret: '${MONGO_EXPRESS_SECRET}'
  ingress:
    hosts:
      - host: mongodb.huna2.com
        paths:
          - '/'
    tls:
      - secretName: mongodb-ingress-tls
        hosts:
          - mongodb.huna2.com

redis-commander:
  redis:
    password: '${REDIS_PASSWORD}'
  httpAuth:
    password: '${REDIS_COMMANDER_PASSWORD}'
  ingress:
    hosts:
      - host: redis.huna2.com
        paths:
          - '/'
    tls:
      - secretName: redis-ingress-tls
        hosts:
          - redis.huna2.com