apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "huna.fullname" . }}-dex-data
  annotations:
    helm.sh/hook: "pre-install"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dex.persistence.size }}