apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "huna.fullname" . }}-dex-data
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.dex.persistence.size }}