apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "huna.fullname" . }}-dex-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dex.persistence.size }}