apiVersion: v1
kind: Service
metadata:
  name: huna-emqx-public
spec:
  ports:
    - name: mqttssl
      protocol: TCP
      port: 8883
      targetPort: mqttssl
  selector:
    app.kubernetes.io/instance: huna
    app.kubernetes.io/name: emqx
  type: LoadBalancer
  sessionAffinity: None
  internalTrafficPolicy: Local
