apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: opa-sidecar-container-policy
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    labelSelector:
      matchLabels:
        opa: "true"
    scope: Namespaced
    namespaces: [ {{ .Release.Namespace }} ]
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
  location: "spec.containers[name:opa]"
  parameters:
    assign:
      value:
        name: "opa"
        imagePullPolicy: IfNotPresent
        image: openpolicyagent/opa:latest-static
        args:
          - "run"
          - "--addr=localhost:8181"
          - "--ignore=.*"
          - "--server"
          - "-w"
          - "/policy"
        ports:
          - name: http
            containerPort: 8181
        volumeMounts:
          - mountPath: /policy
            name: policy
            readOnly: true
---
apiVersion: mutations.gatekeeper.sh/v1
kind: ModifySet
metadata:
  name: opa-sidecar-volume-policy
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    labelSelector:
      matchLabels:
        opa: "true"
    scope: Namespaced
    namespaces: [ {{ .Release.Namespace }} ]
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
  location: "spec.volumes"
  parameters:
    values:
      fromList:
        - name: policy
          configMap:
            name: huna-huna-opa-policy