apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: opa-sidecar
  annotations:
    policies.kyverno.io/title: Inject OPA Sidecar Container
    policies.kyverno.io/category: OPA
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy injects an OPA sidecar container into Pods that match
      an annotation called `openpolicyagent.com/inject: true`.
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: opa-sidecar
      match:
        any:
          - resources:
              kinds:
                - Deployment
      mutate:
        targets:
          - kind: Deployment
            apiVersion: v1
            namespace: {{ .Release.Namespace }}
        patchStrategicMerge:
          spec:
            template:
              metadata:
                annotations:
                  (openpolicyagent.com/inject): "true"
              spec:
                containers:
                  - name: opa
                    image: openpolicyagent/opa:latest-static
                    imagePullPolicy: IfNotPresent
                    args:
                      - "run"
                      - "--addr=localhost:8181"
                      - "--ignore=.*"
                      - "--server"
                      - "-w"
                      - "/policy"
                    ports:
                      - name: http
                        containerPort: 8181
                    volumeMounts:
                      - mountPath: /policy
                        name: policy
                        readOnly: true
                volumes:
                  - name: policy
                    configMap:
                      name: huna-huna-opa-policy
