apiVersion: v1
kind: Secret
metadata:
  name: {{ include "huna.fullname" . }}-opa-secret
  labels:
    {{- include "huna.labels" . | nindent 4 }}
data:
  styraDasToken: {{ .Values.opa.styraDasToken | b64enc | quote }}