apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "huna.fullname" . }}-opa-config
  labels:
    {{- include "huna.labels" . | nindent 4 }}
data:
  config.yaml: |-
    discovery:
      name: discovery
      prefix: /systems/faea3ba894454bb3a61952b0059d933b
      service: styra
    labels:
      system-id: faea3ba894454bb3a61952b0059d933b
      system-type: custom
      app: huna
      env: ${HUNA_ENVIRONMENT}
      pod: ${HOSTNAME}
    services:
      - credentials:
          bearer:
            token: ${STYRA_DAS_TOKEN}
        name: styra
        url: https://0e03ik.svc.styra.com/v1
      - credentials:
          bearer:
            token: ${STYRA_DAS_TOKEN}
        name: styra-bundles
        url: https://0e03ik.svc.styra.com/v1/bundles