apiVersion: v1
kind: Service
metadata:
  name: huna-opa-ui
spec:
  selector:
    app.kubernetes.io/name: huna-ui
    app.kubernetes.io/instance: huna
  type: ClusterIP
  ports:
  - name: opa
    protocol: TCP
    port: 8181
    targetPort: 8181