apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "huna.fullname" . }}-ota
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ota.persistence.size }}