apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "huna.fullname" . }}-ota
  annotations:
    helm.sh/hook: "pre-install"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ota.persistence.size }}