apiVersion: v1
kind: Secret
metadata:
  name: {{ include "huna.fullname" . }}
  labels:
    {{- include "huna.labels" . | nindent 4 }}
data:
  redisPassword: {{ .Values.redis.password | b64enc | quote }}
  mongodbPassword: {{ .Values.mongodb.settings.rootPassword | b64enc | quote }}
  rabbitmqPassword: {{ .Values.rabbitmq.authentication.password | b64enc | quote }}