apiVersion: v1
kind: Secret
metadata:
  name: {{ include "huna.fullname" . }}
  labels:
    {{- include "huna.labels" . | nindent 4 }}
data:
  mongodbPassword: {{ .Values.mongodb.settings.rootPassword | b64enc | quote }}
  LETSENCRYPT_CA: {{ .Values.letsencryptCa | quote }}