apiVersion: v1
kind: Secret
metadata:
  name: {{ include "huna.fullname" . }}
  labels:
    {{- include "huna.labels" . | nindent 4 }}
data:
  mongodbPassword: {{ .Values.mongodb.settings.rootPassword | b64enc | quote }}
  redisPassword: {{ .Values.redis.password | b64enc | quote }}
  rabbitmqPassword: {{ .Values.rabbitmq.password | b64enc | quote }}
  privateVapidKey: {{ .Values.push.privateVapidKey | b64enc | quote }}
  publicVapidKey: {{ .Values.push.publicVapidKey | b64enc | quote }}
  vapidEmail: {{ .Values.push.vapidEmail | b64enc | quote }}