apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "huna.fullname" . }}-ui
  labels:
    {{- include "huna.labels" . | nindent 4 }}
data:
  version: {{ .Chart.Version }}
  appVersion: {{ .Chart.AppVersion }}