apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "huna.fullname" . }}-ui
  labels:
    {{- include "huna.labels" . | nindent 4 }}
data:
  'version.js': 'window.hunaVersion = "{{ .Chart.Version }}"; window.hunaEnv = "{{ .Values.environment }}"; window.hunaVersionDetails = "Release date: {{ now }}. Versions: {{ (include "dependenciesToString" .Values.dependencies) | trim }}"'