name: 'CI/CD'

run-name: '0.0.${{ github.run_number }} - ${{ github.workflow }}'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  helm_build_push:
    uses: mars-office/.github/.github/workflows/helm.yaml@main
    secrets: inherit
    with:
      version: '0.0.${{ github.run_number }}'
  deploy:
    needs: [helm_build_push]
    uses: mars-office/.github/.github/workflows/deploy.yaml@main
    secrets: inherit
    strategy:
      matrix:
        env: ['dev', 'uat', 'prod']
    with:
      version: '0.0.${{ github.run_number }}'
      env: '${{ matrix.env }}'
      namespace: 'huna'
      operation: 'upgrade'
      chartName: 'huna'