name: 'Auto Deploy'

run-name: '0.0.${{ github.event.workflow_run.run_number}} - ${{ github.workflow }}'

on:
  workflow_run:
    workflows: [CI/CD]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        env: ['dev', 'uat', 'prod']
    uses: mars-office/.github/.github/workflows/deploy.yaml@main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    secrets: inherit
    with:
      version: '0.0.${{ github.event.workflow_run.run_number }}'
      env: ${{ matrix.env }}
      chartName: 'huna'
      namespace: 'huna'
      operation: 'upgrade'
