name: 'Deploy'

on:
  workflow_dispatch:


jobs:
  deploy:
    strategy:
      matrix:
        env: ['dev', 'uat', 'prod']
    uses: mars-office/.github/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      version: 'xxxxx'
      env: ${{ matrix.env }}
      chartName: 'huna'
      namespace: 'huna'
