name: 'Deploy'

run-name: '0.0.${{ github.event.workflow_run.run_number || github.event.inputs.version }} - ${{ github.workflow }}'

on:
  workflow_dispatch:
    inputs:
      version:
        type: number
        required: true

  workflow_run:
    workflows: [Helm build and push]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        env: ['dev', 'uat', 'prod']
    uses: mars-office/.github/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      version: '0.0.${{ github.event.workflow_run.run_number }}'
      env: ${{ matrix.env }}
      chartName: 'huna'
      namespace: 'huna'
      operation: 'upgrade'
