name: 'Helm Build and Push'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  helm:
    uses: mars-office/.github/.github/workflows/helm.yaml@main
    secrets: inherit
