name: 'Helm Build and Push'

run-name: 'Helm Build and Push - 0.0.${{ github.run_number }}'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  helm_build_push:
    uses: mars-office/.github/.github/workflows/helm.yaml@main
    secrets: inherit
    with:
      version: '0.0.${{ github.run_number }}'
