name: 'Helm Build and Push'

run-name: '${{ github.repository.name }} - 0.0.${{ github.run_number }} - Helm build and push'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  helm_build_push:
    uses: mars-office/.github/.github/workflows/helm.yaml@main
    secrets: inherit
    with:
      version: '0.0.${{ github.run_number }}'
